"use strict";
const KEY="prosody-tool-v3",OLD_KEY="prosody-tool-v2",THEME_KEY="prosody-theme",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const FONT_FAMILIES={georgia:'Georgia,"Times New Roman",serif',baskerville:'Baskerville,"Baskerville Old Face",Georgia,serif',garamond:'Garamond,"EB Garamond",Georgia,serif',charter:'Charter,"Bitstream Charter",Georgia,serif',palatino:'Palatino,"Palatino Linotype","Book Antiqua",serif',times:'"Times New Roman",Times,serif',system:'-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif',rubik:'Rubik,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'};
const ui={intro:$("#intro"),source:$("#sourceText"),analyze:$("#analyzeBtn"),demo:$("#demoBtn"),theme:$("#themeBtn"),workspace:$("#workspace"),poem:$("#poem"),poemMeta:$("#poemMeta"),summary:$("#poemSummary"),credit:$("#poemCredit"),share:$("#shareBtn"),more:$("#moreBtn"),marks:$("#marksBtn"),typography:$("#typographyBtn"),edit:$("#editBtn"),stats:$("#statsBtn"),help:$("#helpBtn"),undo:$("#undoBtn"),redo:$("#redoBtn"),save:$("#saveState"),statsDialog:$("#statsDialog"),statsBody:$("#statsBody"),editDialog:$("#editDialog"),editText:$("#editText"),applyEdit:$("#applyEditBtn"),shareDialog:$("#shareDialog"),viewDialog:$("#viewDialog"),fontFamily:$("#fontFamilyInput"),fontSize:$("#fontSizeInput"),fontSizeValue:$("#fontSizeValue"),toast:$("#toast")};
const FALLBACK_DEMOS=[{"title":"Autumn Referendum","author":"cheeseonamonkey","content":"Each leaf casts its vote\nThe Autumn Referendum\nThe republic stands.","url":""},{"title":"A Dream Within a Dream","author":"Edgar Allan Poe","content":"Take this kiss upon the brow!\nAnd, in parting from you now,\nThus much let me avow—\nYou are not wrong, who deem\nThat my days have been a dream:","url":"https://www.gutenberg.org/ebooks/76996"}];
let DEMOS=[...FALLBACK_DEMOS].map(normalizePoemEntry),poemLibraryError=null;
function validPoemEntry(p){return p&&typeof p.title==="string"&&p.title.trim()&&typeof p.author==="string"&&p.author.trim()&&typeof p.content==="string"&&p.content.trim()&&typeof p.url==="string"}
function normalizePoemEntry(p){return {title:p.title.trim(),author:p.author.trim(),text:p.content.replace(/\r\n?/g,"\n").trimEnd(),source:p.url.trim()}}
async function loadPoemLibrary(){try{const r=await fetch("./data/poems.json",{cache:"default"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data))throw new Error("poems.json must contain an array");const valid=data.filter(validPoemEntry).map(normalizePoemEntry);if(!valid.length)throw new Error("poems.json contains no valid poems");DEMOS=valid;poemLibraryError=null}catch(err){DEMOS=[...FALLBACK_DEMOS].map(normalizePoemEntry);poemLibraryError=String(err?.message||err)}}
const settings={marks:true,typography:false,counts:true,structure:false,font:"georgia",fontSize:22};
let doc=null,undoStack=[],redoStack=[],saveTimer=null,lastDemoIndex=-1;
const mark={strong:"/",weak:"×",medium:"•"},unicodeMark={strong:"´",weak:"˘",medium:"ˑ"},vowels="aeiouy";
function toast(s){if(!ui.toast)return;ui.toast.textContent=s;ui.toast.classList.add("show");clearTimeout(ui.toast._t);ui.toast._t=setTimeout(()=>ui.toast.classList.remove("show"),1300)}
function pushUndo(){if(!doc)return;undoStack.push(JSON.stringify(doc));if(undoStack.length>100)undoStack.shift();redoStack=[];updateUndo()}
function updateUndo(){if(ui.undo)ui.undo.disabled=!undoStack.length;if(ui.redo)ui.redo.disabled=!redoStack.length}
function saveSoon(){if(!doc||!ui.save)return;ui.save.textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify({doc,settings}));ui.save.textContent="Saved locally"}catch{ui.save.textContent="Local save unavailable"}},90)}
function norm(s){return s.toLowerCase().replace(/[’']/g,"'")}
function casePieces(original,pieces){let out=[],pos=0;for(const p of pieces){out.push(original.slice(pos,pos+p.length));pos+=p.length}if(pos<original.length&&out.length)out[out.length-1]+=original.slice(pos);return out}
function syllabify(word){const lower=norm(word).replace(/[^a-z'-]/g,"");const o={maybe:["may","be"],toves:["toves"],gyre:["gyre"],every:["ev","ery"],even:["e","ven"],hour:["hour"],poem:["po","em"],poetry:["po","e","try"],family:["fam","i","ly"],different:["dif","fer","ent"],fire:["fire"],tired:["tired"],dreadlocks:["dread","locks"],exhaustion:["ex","haus","tion"],beautiful:["beau","ti","ful"],world:["world"],people:["peo","ple"],brillig:["bril","lig"],slithy:["sli","thy"],gimble:["gim","ble"],borogoves:["bor","o","goves"],mimsy:["mim","sy"],frumious:["fru","mi","ous"],manxome:["man","xome"],uffish:["uf","fish"],tulgey:["tul","gey"],frabjous:["frab","jous"],chortled:["chor","tled"],galumphing:["ga","lum","phing"]}[lower];if(o)return casePieces(word,o);let nuclei=[],i=0;while(i<lower.length){if(!vowels.includes(lower[i])){i++;continue}let a=i;while(i<lower.length&&vowels.includes(lower[i]))i++;nuclei.push([a,i])}if(nuclei.length<=1)return[word];if(lower.endsWith("e")&&!lower.endsWith("le")&&nuclei.length>1)nuclei.pop();if(lower.endsWith("ed")&&nuclei.length>1&&!/[td]ed$/.test(lower)){let z=nuclei.at(-1);if(z&&z[0]>=lower.length-2)nuclei.pop()}if(nuclei.length<=1)return[word];let cuts=[];for(let n=0;n<nuclei.length-1;n++){let le=nuclei[n][1],rs=nuclei[n+1][0],cluster=lower.slice(le,rs),cut=cluster.length<=1?le:rs-1;cut=Math.max(1,Math.min(word.length-1,cut));if(!cuts.includes(cut))cuts.push(cut)}let out=[],start=0;for(const c of cuts){out.push(word.slice(start,c));start=c}out.push(word.slice(start));return out.filter(Boolean)}
const wordRE=/[A-Za-zÀ-ÖØ-öø-ÿ]+(?:[’'-][A-Za-zÀ-ÖØ-öø-ÿ]+)*/g;
function manualStress(text){const letters=[...text].filter(ch=>ch.toLowerCase()!==ch.toUpperCase());return letters.length&&letters.every(ch=>ch===ch.toUpperCase())?"strong":"weak"}
function readBracket(source,start){if(source[start]!=="[")return null;let text="";for(let i=start+1;i<source.length;i++){const ch=source[i];if(ch==="\\"&&i+1<source.length&&"[]\\".includes(source[i+1])){text+=source[++i];continue}if(ch==="]")return {text,end:i+1};text+=ch}return null}
function decodeEscapes(s){return s.replace(/\\([\[\]\\])/g,"$1")}
function automaticSyllables(raw){const lexical=typeof IambicStress!=="undefined"?IambicStress.forWord(raw):null;let pieces=syllabify(raw);if(lexical&&typeof IambicSyllables!=="undefined")pieces=IambicSyllables.toCount(raw,pieces,lexical.length);const aligned=lexical&&lexical.length===pieces.length?lexical:null;return pieces.map((text,i)=>({text,stress:aligned?.[i]??null,boundary:null,manual:false}))}
function parsePlainChunk(chunk){const visible=decodeEscapes(chunk),segs=[];let last=0,m;wordRE.lastIndex=0;while((m=wordRE.exec(visible))){if(m.index>last)segs.push({kind:"gap",text:visible.slice(last,m.index)});const raw=m[0];segs.push({kind:"word",raw,manual:false,syllables:automaticSyllables(raw)});last=m.index+raw.length}if(last<visible.length)segs.push({kind:"gap",text:visible.slice(last)});return segs}
function parseLine(source){const segments=[];let plain="",i=0;const flush=()=>{if(plain){segments.push(...parsePlainChunk(plain));plain=""}};while(i<source.length){if(source[i]==="\\"&&i+1<source.length&&"[]\\".includes(source[i+1])){plain+=source.slice(i,i+2);i+=2;continue}if(source[i]!=="["){plain+=source[i++];continue}const first=readBracket(source,i);if(!first){plain+=source[i++];continue}flush();const syllables=[];let raw="",j=i,part=first;while(part){raw+=part.text;syllables.push({text:part.text,stress:manualStress(part.text),boundary:null,manual:true});j=part.end;if(source[j]!=="[")break;part=readBracket(source,j);if(!part)break}segments.push({kind:"word",raw,manual:true,syllables});i=j}flush();return {raw:segments.map(seg=>seg.kind==="gap"?seg.text:seg.syllables.map(s=>s.text).join("")).join(""),source,segments}}
function parseText(text){const source=String(text??"").replace(/\r\n?/g,"\n");const blocks=source.split(/\n\s*\n/).filter((s,i,a)=>s.length||a.length===1);const stanzas=blocks.map(s=>({lines:s.split("\n").map(parseLine)}));const visible=stanzas.map(st=>st.lines.map(l=>l.raw).join("\n")).join("\n\n");return {version:3,source,text:visible,stanzas}}
function allSyllables(d=doc){let out=[];if(!d)return out;d.stanzas.forEach((st,si)=>st.lines.forEach((ln,li)=>ln.segments.forEach((seg,gi)=>{if(seg.kind!=="word")return;seg.syllables.forEach((sy,yi)=>out.push({key:norm(sy.text).replace(/[^a-z0-9]/g,""),sy,path:[si,li,gi,yi]}))})));return out}
function reconcile(text){const prior=doc?.meta||{},next=parseText(text);next.meta={...prior,author:"Anonymous",source:"",edited:true};return next}
function lineStats(line){let s=line.segments.flatMap(x=>x.kind==="word"?x.syllables:[]);return{syllables:s.length,strong:s.filter(x=>x.stress==="strong").length,medium:s.filter(x=>x.stress==="medium").length,weak:s.filter(x=>x.stress==="weak").length}}
function stanzaStats(st){let l=st.lines.map(lineStats);return{lines:l.length,syllables:l.reduce((a,x)=>a+x.syllables,0),strong:l.reduce((a,x)=>a+x.strong,0),medium:l.reduce((a,x)=>a+x.medium,0),weak:l.reduce((a,x)=>a+x.weak,0),syllablePattern:l.map(x=>x.syllables).join(" · ")}}
function docStats(d=doc){let sts=d.stanzas.map(stanzaStats),ls=d.stanzas.flatMap(s=>s.lines.map(lineStats)),sy=ls.reduce((a,x)=>a+x.syllables,0);return{stanzas:sts.length,lines:ls.length,syllables:sy,strong:ls.reduce((a,x)=>a+x.strong,0),medium:ls.reduce((a,x)=>a+x.medium,0),weak:ls.reduce((a,x)=>a+x.weak,0),avg:ls.length?sy/ls.length:0,min:ls.length?Math.min(...ls.map(x=>x.syllables)):0,max:ls.length?Math.max(...ls.map(x=>x.syllables)):0,stanzasData:sts}}
function unicodeAnnotatedLine(line){return line.segments.map(seg=>{if(seg.kind==="gap")return seg.text;return seg.syllables.map(s=>(unicodeMark[s.stress]||"")+s.text+(s.boundary==="foot"?"│":s.boundary==="caesura"?"‖":"")).join("·")}).join("")}
function annotatedText(d=doc){if(!d)return"";const out=[];if(d.meta?.title)out.push(d.meta.title,"");d.stanzas.forEach((st,si)=>{st.lines.forEach(line=>out.push(unicodeAnnotatedLine(line)));if(si<d.stanzas.length-1)out.push("")});out.push("",`— ${d.meta?.author||"Anonymous"}`);return out.join("\n")}
function migrateSettings(saved={}){const font=Object.hasOwn(FONT_FAMILIES,saved.font)?saved.font:"georgia",fontSize=Math.max(16,Math.min(30,Number(saved.fontSize)||22));const out={marks:saved.marks!==false,typography:!!saved.typography,counts:saved.counts!==false,structure:false,font,fontSize};if(Object.hasOwn(saved,"structure"))out.structure=!!saved.structure;else if(Object.hasOwn(saved,"stanzas")||Object.hasOwn(saved,"boundaries"))out.structure=saved.stanzas!==false||saved.boundaries!==false;return out}
function migrateDoc(saved){if(!saved)return null;if(saved.version>=3&&typeof saved.source==="string")return saved;const next=parseText(saved.source??saved.text??"");next.meta=saved.meta||null;return next}
function el(tag,cls,text){let e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function poemFontCss(){return FONT_FAMILIES[settings.font]||FONT_FAMILIES.georgia}
function showWorkspace(){ui.intro.classList.add("hidden");ui.workspace.classList.remove("hidden");[ui.share,ui.more].forEach(x=>x&&x.classList.remove("hidden"));updateUndo()}
