function openStats(){let s=docStats();ui.statsBody.innerHTML="";let grid=el("div","stats-grid");[["Syllables",s.syllables],["Strong beats",s.strong],["Lines",s.lines],["Stanzas",s.stanzas],["Avg / line",s.avg.toFixed(1)],["Line range",`${s.min}–${s.max}`]].forEach(([label,val])=>{let box=el("div","stat");box.append(el("b","",val),el("span","",label));grid.appendChild(box)});ui.statsBody.appendChild(grid);let list=el("div","pattern-list");list.appendChild(el("div","field-label","Stanza syllable patterns"));s.stanzasData.forEach((st,i)=>{let r=el("div","pattern-row");r.append(el("span","",`Stanza ${i+1}`),el("b","",st.syllablePattern||"—"));list.appendChild(r)});ui.statsBody.appendChild(list);ui.statsDialog.showModal()}

let themePref=(()=>{try{const saved=localStorage.getItem(THEME_KEY);if(saved==="dark"||saved==="light")return saved}catch{}return matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"})();
function applyTheme(){document.documentElement.dataset.theme=themePref;const dark=themePref==="dark";ui.theme.textContent=dark?"☾":"☀";ui.theme.title=`Theme: ${themePref} · tap for ${dark?"light":"dark"}`;ui.theme.setAttribute("aria-label",ui.theme.title);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?"#121210":"#f6f5f1";try{localStorage.setItem(THEME_KEY,themePref)}catch{}}
function toggleTheme(){themePref=themePref==="dark"?"light":"dark";applyTheme()}
function downloadBlob(name,blob){let a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadText(name,content){downloadBlob(name,new Blob([content],{type:"text/plain;charset=utf-8"}))}
function undo(){if(!undoStack.length)return;redoStack.push(JSON.stringify(doc));doc=JSON.parse(undoStack.pop());ui.source.value=doc.source??doc.text??"";render();updateUndo()}
function redo(){if(!redoStack.length)return;undoStack.push(JSON.stringify(doc));doc=JSON.parse(redoStack.pop());ui.source.value=doc.source??doc.text??"";render();updateUndo()}
function loadDemo(d,{quiet=false}={}){doc=parseText(d.text);doc.meta={title:d.title,author:d.author,source:d.source,license:d.license,excerpt:!!d.excerpt};undoStack=[];redoStack=[];ui.source.value=d.text;showWorkspace();render();if(!quiet)toast(`${d.author} · ${d.title}`)}
function randomDemo(){if(!DEMOS.length)return;let i=Math.floor(Math.random()*DEMOS.length);if(DEMOS.length>1&&i===lastDemoIndex)i=(i+1+Math.floor(Math.random()*(DEMOS.length-1)))%DEMOS.length;lastDemoIndex=i;loadDemo(DEMOS[i],{quiet:true})}
function restore(){try{let s=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||"null");if(!s?.doc)return false;doc=migrateDoc(s.doc);Object.assign(settings,migrateSettings(s.settings||{}));ui.source.value=doc.source??doc.text??"";showWorkspace();render();return true}catch{return false}}

function themePalette(){const dark=document.documentElement.dataset.theme==="dark";return dark?{bg:"#121210",ink:"#f2f0e9",muted:"#b8b5ab",hair:"#383731"}:{bg:"#f6f5f1",ink:"#171715",muted:"#5f5d57",hair:"#d8d6cf"}}
function wrapCanvasText(ctx,text,maxWidth){const words=text.split(/(\s+)/),lines=[];let current="";for(const word of words){const next=current+word;if(current&&ctx.measureText(next).width>maxWidth){lines.push(current.trimEnd());current=word.trimStart()}else current=next}if(current||!lines.length)lines.push(current);return lines}
function makeExportCanvas(){const p=themePalette(),logicalWidth=1400,pad=80,textWidth=logicalWidth-pad*2;const rows=[];if(doc.meta?.title){rows.push({text:doc.meta.title,kind:"title"});if(doc.meta.author)rows.push({text:`— ${doc.meta.author}`,kind:"meta"});rows.push({text:"",kind:"gap"})}doc.stanzas.forEach((st,si)=>{st.lines.forEach(line=>rows.push({text:unicodeAnnotatedLine(line),kind:"line"}));if(si<doc.stanzas.length-1)rows.push({text:"",kind:"gap"})});const probe=document.createElement("canvas").getContext("2d");probe.font='34px Georgia, "Times New Roman", serif';const expanded=[];for(const r of rows){if(r.kind!=="line"){expanded.push(r);continue}for(const text of wrapCanvasText(probe,r.text,textWidth))expanded.push({text,kind:"line"})}let h=pad+expanded.reduce((n,r)=>n+(r.kind==="title"?58:r.kind==="meta"?36:r.kind==="gap"?34:50),0)+pad;const scale=2,c=document.createElement("canvas");c.width=logicalWidth*scale;c.height=Math.max(400,h)*scale;const ctx=c.getContext("2d");ctx.scale(scale,scale);ctx.fillStyle=p.bg;ctx.fillRect(0,0,logicalWidth,c.height/scale);let y=pad;for(const r of expanded){if(r.kind==="title"){ctx.font='700 42px Georgia, "Times New Roman", serif';ctx.fillStyle=p.ink;y+=42;ctx.fillText(r.text,pad,y);y+=16}else if(r.kind==="meta"){ctx.font='24px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillStyle=p.muted;y+=24;ctx.fillText(r.text,pad,y);y+=12}else if(r.kind==="gap"){y+=34}else{ctx.font='34px Georgia, "Times New Roman", serif';ctx.fillStyle=p.ink;y+=36;ctx.fillText(r.text,pad,y);y+=14}}return c}
function downloadPng(){const c=makeExportCanvas();c.toBlob(blob=>blob?downloadBlob("iambic.png",blob):toast("Image export unavailable."),"image/png")}
function printPdf(){const w=window.open("","_blank");if(!w){toast("Allow pop-ups to save PDF.");return}const data=makeExportCanvas().toDataURL("image/png"),p=themePalette();w.document.write(`<!doctype html><title>Iambic export</title><style>@page{margin:0}html,body{margin:0;background:${p.bg}}img{display:block;width:100%;height:auto;-webkit-print-color-adjust:exact;print-color-adjust:exact}</style><img src="${data}" onload="setTimeout(()=>window.print(),50)">`);w.document.close()}

ui.demo.addEventListener("click",randomDemo);ui.theme.addEventListener("click",toggleTheme);applyTheme();
ui.analyze.addEventListener("click",()=>{let text=ui.source.value;if(!text.trim()){toast("Add some text first.");return}doc=parseText(text);doc.meta=null;undoStack=[];redoStack=[];showWorkspace();render()});
$("#viewStrip").addEventListener("click",e=>{let b=e.target.closest("button");if(!b?.dataset.toggle)return;settings[b.dataset.toggle]=!settings[b.dataset.toggle];render()});
ui.stats.addEventListener("click",openStats);ui.help.addEventListener("click",()=>$("#helpDialog").showModal());ui.edit.addEventListener("click",()=>{ui.editText.value=doc.source??doc.text??"";ui.editDialog.showModal()});
ui.applyEdit.addEventListener("click",()=>{let text=ui.editText.value;if(!text.trim()){toast("The poem cannot be empty.");return}pushUndo();doc=reconcile(text);ui.source.value=text;ui.editDialog.close();render()});
ui.exp.addEventListener("click",()=>ui.exportDialog.showModal());ui.undo.addEventListener("click",undo);ui.redo.addEventListener("click",redo);
$("#copyAnnotatedBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(annotatedText());toast("Copied.")}catch{toast("Clipboard unavailable.")}});
$("#downloadTxtBtn").addEventListener("click",()=>downloadText("iambic.txt",annotatedText()));
$("#downloadPngBtn").addEventListener("click",downloadPng);$("#printPdfBtn").addEventListener("click",printPdf);
$$('[data-close]').forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.close).close()));
document.addEventListener("keydown",e=>{if(!doc||document.querySelector("dialog[open]"))return;let mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}else if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}});
async function init(){try{await loadPoemLibrary();restore()}finally{document.documentElement.classList.remove("booting")}}
init();
