function openStats(){let s=docStats();ui.statsBody.innerHTML="";let grid=el("div","stats-grid");[["Syllables",s.syllables],["Primary stress",s.strong],["Secondary stress",s.medium],["Lines",s.lines],["Stanzas",s.stanzas],["Avg / line",s.avg.toFixed(1)],["Line range",`${s.min}–${s.max}`]].forEach(([label,val])=>{let box=el("div","stat");box.append(el("b","",val),el("span","",label));grid.appendChild(box)});ui.statsBody.appendChild(grid);let list=el("div","pattern-list");list.appendChild(el("div","field-label","Stanza syllable patterns"));s.stanzasData.forEach((st,i)=>{let r=el("div","pattern-row");r.append(el("span","",`Stanza ${i+1}`),el("b","",st.syllablePattern||"—"));list.appendChild(r)});ui.statsBody.appendChild(list);ui.statsDialog.showModal()}

let themePref=(()=>{try{const saved=localStorage.getItem(THEME_KEY);if(saved==="dark"||saved==="light")return saved}catch{}return matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"})();
function applyTheme(){document.documentElement.dataset.theme=themePref;const dark=themePref==="dark";ui.theme.textContent=dark?"☾":"☀";ui.theme.title=`Theme: ${themePref} · tap for ${dark?"light":"dark"}`;ui.theme.setAttribute("aria-label",ui.theme.title);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?"#121210":"#f6f5f1";try{localStorage.setItem(THEME_KEY,themePref)}catch{}}
function toggleTheme(){themePref=themePref==="dark"?"light":"dark";applyTheme()}
function downloadBlob(name,blob){let a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadText(name,content){downloadBlob(name,new Blob([content],{type:"text/plain;charset=utf-8"}))}
function undo(){if(!undoStack.length)return;redoStack.push(JSON.stringify(doc));doc=JSON.parse(undoStack.pop());ui.source.value=doc.source??doc.text??"";render();updateUndo()}
function redo(){if(!redoStack.length)return;undoStack.push(JSON.stringify(doc));doc=JSON.parse(redoStack.pop());ui.source.value=doc.source??doc.text??"";render();updateUndo()}
function loadDemo(d,{quiet=false}={}){doc=parseText(d.text);doc.meta={title:d.title,author:d.author,source:d.source};undoStack=[];redoStack=[];ui.source.value=d.text;showWorkspace();render();if(!quiet)toast(`${d.author} · ${d.title}`)}
function randomDemo(){if(!DEMOS.length)return;let i=Math.floor(Math.random()*DEMOS.length);if(DEMOS.length>1&&i===lastDemoIndex)i=(i+1+Math.floor(Math.random()*(DEMOS.length-1)))%DEMOS.length;lastDemoIndex=i;loadDemo(DEMOS[i],{quiet:true})}
function restore(){try{let s=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||"null");if(!s?.doc)return false;doc=migrateDoc(s.doc);Object.assign(settings,migrateSettings(s.settings||{}));ui.source.value=doc.source??doc.text??"";showWorkspace();render();return true}catch{return false}}
function closeView(){if(ui.viewDialog?.open)ui.viewDialog.close()}
function openFromView(dialog){closeView();dialog.showModal()}
function openEdit(){stripPoemMeta();ui.editText.value=doc.source??doc.text??"";ui.editDialog.showModal()}

function themePalette(){const dark=document.documentElement.dataset.theme==="dark";return dark?{bg:"#121210",ink:"#f2f0e9",muted:"#b8b5ab",hair:"#383731"}:{bg:"#f6f5f1",ink:"#171715",muted:"#5f5d57",hair:"#d8d6cf"}}
function wrapCanvasText(ctx,text,maxWidth){const words=text.split(/(\s+)/),lines=[];let current="";for(const word of words){const next=current+word;if(current&&ctx.measureText(next).width>maxWidth){lines.push(current.trimEnd());current=word.trimStart()}else current=next}if(current||!lines.length)lines.push(current);return lines}
function makeExportCanvas(){const p=themePalette(),logicalWidth=1400,pad=80,textWidth=logicalWidth-pad*2,linePx=Math.round(settings.fontSize*1.55),lineStep=Math.round(linePx*Math.max(1.15,settings.lineHeight)),font=poemFontCss();const rows=[];if(doc.meta?.title){rows.push({text:doc.meta.title,kind:"title"});rows.push({text:"",kind:"gap"})}doc.stanzas.forEach((st,si)=>{st.lines.forEach(line=>rows.push({text:unicodeAnnotatedLine(line),kind:"line"}));if(si<doc.stanzas.length-1)rows.push({text:"",kind:"gap"})});rows.push({text:`— ${doc.meta?.author||"Anonymous"}`,kind:"meta"});const probe=document.createElement("canvas").getContext("2d");probe.font=`${linePx}px ${font}`;const expanded=[];for(const r of rows){if(r.kind!=="line"||!settings.wrap){expanded.push(r);continue}for(const text of wrapCanvasText(probe,r.text,textWidth))expanded.push({text,kind:"line"})}let h=pad+expanded.reduce((n,r)=>n+(r.kind==="title"?Math.round(linePx*1.8):r.kind==="meta"?36:r.kind==="gap"?Math.round(lineStep*.7):lineStep),0)+pad;const scale=2,c=document.createElement("canvas");c.width=logicalWidth*scale;c.height=Math.max(400,h)*scale;const ctx=c.getContext("2d");ctx.scale(scale,scale);ctx.fillStyle=p.bg;ctx.fillRect(0,0,logicalWidth,c.height/scale);let y=pad;for(const r of expanded){if(r.kind==="title"){const titlePx=Math.round(linePx*1.22);ctx.font=`700 ${titlePx}px ${font}`;ctx.fillStyle=p.ink;y+=titlePx;ctx.fillText(r.text,pad,y);y+=Math.round(linePx*.45)}else if(r.kind==="meta"){ctx.font='24px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';ctx.fillStyle=p.muted;y+=24;ctx.fillText(r.text,pad,y);y+=12}else if(r.kind==="gap"){y+=Math.round(lineStep*.7)}else{ctx.font=`${linePx}px ${font}`;ctx.fillStyle=p.ink;y+=Math.round(linePx*1.05);ctx.fillText(r.text,pad,y);y+=Math.max(8,lineStep-Math.round(linePx*1.05))}}return c}
async function ensureFonts(){try{if(document.fonts)await document.fonts.ready}catch{}}
async function downloadPng(){await ensureFonts();const c=makeExportCanvas();c.toBlob(blob=>blob?downloadBlob("iambic.png",blob):toast("Image export unavailable."),"image/png")}
async function printPdf(){const w=window.open("","_blank");if(!w){toast("Allow pop-ups to save PDF.");return}await ensureFonts();const data=makeExportCanvas().toDataURL("image/png"),p=themePalette();w.document.write(`<!doctype html><title>Iambic export</title><style>@page{margin:0}html,body{margin:0;background:${p.bg}}img{display:block;width:100%;height:auto;-webkit-print-color-adjust:exact;print-color-adjust:exact}</style><img src="${data}" onload="setTimeout(()=>window.print(),50)">`);w.document.close()}

ui.demo.addEventListener("click",randomDemo);ui.theme.addEventListener("click",toggleTheme);applyTheme();
ui.analyze.addEventListener("click",()=>{let text=ui.source.value;if(!text.trim()){toast("Add some text first.");return}doc=parseText(text);doc.meta=null;undoStack=[];redoStack=[];showWorkspace();render()});
ui.more.addEventListener("click",()=>ui.viewDialog.showModal());ui.share.addEventListener("click",()=>ui.shareDialog.showModal());
ui.marks.addEventListener("click",()=>{settings.marks=!settings.marks;render()});ui.typography.addEventListener("click",()=>{settings.typography=!settings.typography;render()});ui.counts.addEventListener("click",()=>{settings.counts=!settings.counts;render()});ui.structure.addEventListener("click",()=>{settings.structure=!settings.structure;render()});
ui.fontFamily.addEventListener("change",()=>{if(Object.hasOwn(FONT_FAMILIES,ui.fontFamily.value)){settings.font=ui.fontFamily.value;render()}});
ui.fontSize.addEventListener("input",()=>{settings.fontSize=Math.max(16,Math.min(30,Number(ui.fontSize.value)||22));render()});
ui.lineHeight.addEventListener("input",()=>{settings.lineHeight=Math.max(1.1,Math.min(1.6,Number(ui.lineHeight.value)||1.29));render()});
ui.symbolScale.addEventListener("input",()=>{settings.symbolScale=Math.max(.65,Math.min(1.6,(Number(ui.symbolScale.value)||100)/100));render()});
ui.syllableGap.addEventListener("input",()=>{settings.syllableGap=Math.max(0,Math.min(.16,(Number(ui.syllableGap.value)||0)/100));render()});
ui.typeStrength.addEventListener("input",()=>{settings.typeStrength=Math.max(0,Math.min(1,(Number(ui.typeStrength.value)||0)/100));render()});
ui.wrap.addEventListener("change",()=>{settings.wrap=ui.wrap.checked;render()});ui.separators.addEventListener("change",()=>{settings.separators=ui.separators.checked;render()});
ui.stats.addEventListener("click",()=>{closeView();openStats()});ui.help.addEventListener("click",()=>openFromView($("#helpDialog")));ui.headEdit.addEventListener("click",openEdit);
ui.applyEdit.addEventListener("click",()=>{let text=ui.editText.value;if(!text.trim()){toast("The poem cannot be empty.");return}pushUndo();doc=reconcile(text);ui.source.value=text;ui.editDialog.close();render()});
ui.undo.addEventListener("click",undo);ui.redo.addEventListener("click",redo);
$("#copyAnnotatedBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(annotatedText());toast("Copied.")}catch{toast("Clipboard unavailable.")}});
$("#downloadTxtBtn").addEventListener("click",()=>downloadText("iambic.txt",annotatedText()));
$("#downloadPngBtn").addEventListener("click",downloadPng);$("#printPdfBtn").addEventListener("click",printPdf);
$$('[data-close]').forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.close).close()));
document.addEventListener("keydown",e=>{if(!doc||document.querySelector("dialog[open]"))return;let mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}else if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}});
async function init(){try{const tasks=[loadPoemLibrary()];if(typeof IambicLexicon!=="undefined")tasks.push(IambicLexicon.load());await Promise.allSettled(tasks);restore()}finally{document.documentElement.classList.remove("booting")}}
init();
