"use strict";
const KEY="prosody-tool-v2",THEME_KEY="prosody-theme",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ui={intro:$("#intro"),source:$("#sourceText"),analyze:$("#analyzeBtn"),demo:$("#demoBtn"),copyMd:$("#copyMdBtn"),theme:$("#themeBtn"),demoDialog:$("#demoDialog"),demoSearch:$("#demoSearch"),demoList:$("#demoList"),demoCount:$("#demoCount"),workspace:$("#workspace"),poem:$("#poem"),poemMeta:$("#poemMeta"),summary:$("#poemSummary"),viewWrap:$("#viewWrap"),edit:$("#editBtn"),stats:$("#statsBtn"),help:$("#helpBtn"),exp:$("#exportBtn"),undo:$("#undoBtn"),redo:$("#redoBtn"),context:$("#contextBar"),save:$("#saveState"),statsDialog:$("#statsDialog"),statsBody:$("#statsBody"),editDialog:$("#editDialog"),editText:$("#editText"),applyEdit:$("#applyEditBtn"),wordDialog:$("#wordDialog"),wordInput:$("#wordSplitInput"),applyWord:$("#applyWordBtn"),exportDialog:$("#exportDialog"),toast:$("#toast"),syllablesBtn:$("#syllablesBtn")};
const FALLBACK_DEMOS=[{"title":"Autumn Referendum","author":"Dev","text":"Each leaf casts its vote.\nThe Autumn Referendum\nThe republic stands.","license":"Copyright © Dev; included with permission","tags":["haiku · 5–7–5"]},{"title":"A Dream Within a Dream","author":"Edgar Allan Poe","text":"Take this kiss upon the brow!\nAnd, in parting from you now,\nThus much let me avow—\nYou are not wrong, who deem\nThat my days have been a dream:\nYet if hope has flown away\nIn a night, or in a day,\nIn a vision, or in none,\nIs it therefore the less gone?\nAll that we see or seem\nIs but a dream within a dream.\n\nI stand amid the roar\nOf a surf-tormented shore,\nAnd I hold within my hand\nGrains of the golden sand—\nHow few! yet how they creep\nThrough my fingers to the deep,\nWhile I weep—while I weep!\nO God! can I not grasp\nThem with a tighter clasp?\nO God! can I not save\nOne from the pitiless wave?\nIs all that we see or seem\nBut a dream within a dream?","license":"Public Domain","tags":["mixed short lines"],"source":"https://www.gutenberg.org/ebooks/76996"}];
let DEMOS=[...FALLBACK_DEMOS],poemLibraryError=null;
function validPoemEntry(p){return p&&typeof p.title==="string"&&p.title.trim()&&typeof p.author==="string"&&p.author.trim()&&typeof p.text==="string"&&p.text.trim()&&typeof p.license==="string"&&p.license.trim()}
function normalizePoemEntry(p){return {title:p.title.trim(),author:p.author.trim(),text:p.text.replace(/\r\n?/g,"\n").trimEnd(),license:p.license.trim(),tags:Array.isArray(p.tags)?p.tags.filter(x=>typeof x==="string"&&x.trim()).map(x=>x.trim()):[],source:typeof p.source==="string"?p.source:"",excerpt:!!p.excerpt}}
async function loadPoemLibrary(){
  try{
    const r=await fetch("./poems.json",{cache:"default"});
    if(!r.ok)throw new Error(`HTTP ${r.status}`);
    const data=await r.json();
    if(!Array.isArray(data))throw new Error("poems.json must contain an array");
    const valid=data.filter(validPoemEntry).map(normalizePoemEntry);
    if(!valid.length)throw new Error("poems.json contains no valid poems");
    DEMOS=valid;poemLibraryError=null;
  }catch(err){
    DEMOS=[...FALLBACK_DEMOS];poemLibraryError=String(err?.message||err);
  }
}
const settings={marks:true,typography:false,counts:true,stanzas:true,boundaries:true};let doc=null,selected=null,undoStack=[],redoStack=[],longTimer=null,suppressClick=false,saveTimer=null;
const order=[null,"strong","weak","medium"],mark={strong:"/",weak:"×",medium:"•"},vowels="aeiouy";
function toast(s){ui.toast.textContent=s;ui.toast.classList.add("show");clearTimeout(ui.toast._t);ui.toast._t=setTimeout(()=>ui.toast.classList.remove("show"),1500)}
function pushUndo(){if(!doc)return;undoStack.push(JSON.stringify(doc));if(undoStack.length>100)undoStack.shift();redoStack=[];updateUndo()}function updateUndo(){ui.undo.disabled=!undoStack.length;ui.redo.disabled=!redoStack.length}
function saveSoon(){ui.save.textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify({doc,settings}));ui.save.textContent="Saved locally"}catch{ui.save.textContent="Local save unavailable"}},100)}
function norm(s){return s.toLowerCase().replace(/[’']/g,"'")}
function casePieces(original,pieces){let out=[],pos=0;for(const p of pieces){out.push(original.slice(pos,pos+p.length));pos+=p.length}if(pos<original.length)out[out.length-1]+=original.slice(pos);return out}
function syllabify(word){const lower=norm(word).replace(/[^a-z'-]/g,"");const o={every:["ev","ery"],even:["e","ven"],hour:["hour"],poem:["po","em"],poetry:["po","e","try"],family:["fam","i","ly"],different:["dif","fer","ent"],fire:["fire"],tired:["tired"],dreadlocks:["dread","locks"],exhaustion:["ex","haus","tion"],beautiful:["beau","ti","ful"],world:["world"],people:["peo","ple"]}[lower];if(o)return casePieces(word,o);let nuclei=[],i=0;while(i<lower.length){if(!vowels.includes(lower[i])){i++;continue}let a=i;while(i<lower.length&&vowels.includes(lower[i]))i++;nuclei.push([a,i])}if(nuclei.length<=1)return[word];if(lower.endsWith("e")&&!lower.endsWith("le")&&nuclei.length>1)nuclei.pop();if(lower.endsWith("ed")&&nuclei.length>1&&!/[td]ed$/.test(lower)){let z=nuclei.at(-1);if(z&&z[0]>=lower.length-2)nuclei.pop()}if(nuclei.length<=1)return[word];let cuts=[];for(let n=0;n<nuclei.length-1;n++){let le=nuclei[n][1],rs=nuclei[n+1][0],cluster=lower.slice(le,rs),cut=cluster.length<=1?le:rs-1;cut=Math.max(1,Math.min(word.length-1,cut));if(!cuts.includes(cut))cuts.push(cut)}let out=[],start=0;for(const c of cuts){out.push(word.slice(start,c));start=c}out.push(word.slice(start));return out.filter(Boolean)}
const wordRE=/[A-Za-zÀ-ÖØ-öø-ÿ]+(?:[’'-][A-Za-zÀ-ÖØ-öø-ÿ]+)*/g;
function parseLine(text){let segs=[],last=0,m;wordRE.lastIndex=0;while((m=wordRE.exec(text))){if(m.index>last)segs.push({kind:"gap",text:text.slice(last,m.index)});let raw=m[0];segs.push({kind:"word",raw,syllables:syllabify(raw).map(text=>({text,stress:null,boundary:null}))});last=m.index+raw.length}if(last<text.length)segs.push({kind:"gap",text:text.slice(last)});return{raw:text,segments:segs}}
function parseText(text){let t=text.replace(/\r\n?/g,"\n").replace(/\n{3,}/g,"\n\n").trimEnd();return{version:1,text:t,stanzas:t.split(/\n\s*\n/).map(s=>({lines:s.split("\n").map(parseLine)}))}}
function allSyllables(d=doc){let out=[];if(!d)return out;d.stanzas.forEach((st,si)=>st.lines.forEach((ln,li)=>ln.segments.forEach((seg,gi)=>{if(seg.kind!=="word")return;seg.syllables.forEach((sy,yi)=>out.push({key:norm(sy.text).replace(/[^a-z0-9]/g,""),sy,path:[si,li,gi,yi]}))})));return out}
function reconcile(text){let old=allSyllables(doc),next=parseText(text),neu=allSyllables(next),n=old.length,m=neu.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=old[i].key===neu[j].key?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);for(let i=0,j=0;i<n&&j<m;){if(old[i].key===neu[j].key){neu[j].sy.stress=old[i].sy.stress;neu[j].sy.boundary=old[i].sy.boundary;i++;j++}else if(dp[i+1][j]>=dp[i][j+1])i++;else j++}return next}
function getSyllable(p){if(!p)return null;let[a,b,c,d]=p;return doc?.stanzas?.[a]?.lines?.[b]?.segments?.[c]?.syllables?.[d]||null}function getWord(p){if(!p)return null;let[a,b,c]=p;return doc?.stanzas?.[a]?.lines?.[b]?.segments?.[c]||null}
function lineStats(line){let s=line.segments.flatMap(x=>x.kind==="word"?x.syllables:[]);return{syllables:s.length,strong:s.filter(x=>x.stress==="strong").length,medium:s.filter(x=>x.stress==="medium").length,weak:s.filter(x=>x.stress==="weak").length}}
function stanzaStats(st){let l=st.lines.map(lineStats);return{lines:l.length,syllables:l.reduce((a,x)=>a+x.syllables,0),strong:l.reduce((a,x)=>a+x.strong,0),medium:l.reduce((a,x)=>a+x.medium,0),weak:l.reduce((a,x)=>a+x.weak,0),syllablePattern:l.map(x=>x.syllables).join(" · "),beatPattern:l.map(x=>x.strong).join(" · ")}}
function docStats(){let sts=doc.stanzas.map(stanzaStats),ls=doc.stanzas.flatMap(s=>s.lines.map(lineStats)),sy=ls.reduce((a,x)=>a+x.syllables,0);return{stanzas:sts.length,lines:ls.length,syllables:sy,strong:ls.reduce((a,x)=>a+x.strong,0),medium:ls.reduce((a,x)=>a+x.medium,0),weak:ls.reduce((a,x)=>a+x.weak,0),avg:ls.length?sy/ls.length:0,min:ls.length?Math.min(...ls.map(x=>x.syllables)):0,max:ls.length?Math.max(...ls.map(x=>x.syllables)):0,stanzasData:sts}}
function el(tag,cls,text){let e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function showWorkspace(){ui.intro.classList.add("hidden");ui.workspace.classList.remove("hidden");ui.viewWrap.classList.remove("hidden");[ui.edit,ui.stats,ui.help,ui.exp,ui.undo,ui.redo,ui.copyMd].forEach(x=>x.classList.remove("hidden"));updateUndo()}
