function openStats(){let s=docStats();ui.statsBody.innerHTML="";let grid=el("div","stats-grid");[["Syllables",s.syllables],["Strong beats",s.strong],["Lines",s.lines],["Stanzas",s.stanzas],["Avg / line",s.avg.toFixed(1)],["Line range",`${s.min}–${s.max}`]].forEach(([label,val])=>{let box=el("div","stat");let b=el("b","",val),sp=el("span","",label);box.append(b,sp);grid.appendChild(box)});ui.statsBody.appendChild(grid);let list=el("div","pattern-list");list.appendChild(el("div","field-label","Stanza syllable patterns"));s.stanzasData.forEach((st,i)=>{let r=el("div","pattern-row");r.append(el("span","",`Stanza ${i+1}`),el("b","",st.syllablePattern||"—"));list.appendChild(r)});ui.statsBody.appendChild(list);ui.statsDialog.showModal()}
function annotatedText(){let out=[];doc.stanzas.forEach(st=>{st.lines.forEach(line=>{let s=line.segments.flatMap(x=>x.kind==="word"?x.syllables:[]);out.push(s.map(x=>mark[x.stress]||"·").join(" "));out.push(line.raw)});out.push("")});return out.join("\n").trimEnd()}
function markdownText(){let out=[];if(doc.meta?.title)out.push(`### ${doc.meta.title}${doc.meta.author?` — ${doc.meta.author}`:""}`,"");doc.stanzas.forEach(st=>{st.lines.forEach(line=>{let syllables=line.segments.flatMap(x=>x.kind==="word"?x.syllables:[]),marks=syllables.map(x=>mark[x.stress]||"·").join(" ");let text=line.segments.map(seg=>{if(seg.kind==="gap")return seg.text;return seg.syllables.map(s=>s.stress==="strong"?`**${s.text}**`:s.stress==="medium"?`*${s.text}*`:s.text).join("")}).join("");out.push(`\`${marks}\`  `,text+"  ")});out.push("")});return out.join("\n").trimEnd()}
async function copyMarkdown(){if(!doc)return;try{await navigator.clipboard.writeText(markdownText());toast("Markdown copied.")}catch{toast("Clipboard unavailable.")}}
let themePref=(()=>{try{return localStorage.getItem(THEME_KEY)||"system"}catch{return"system"}})();
function applyTheme(){if(themePref==="light"||themePref==="dark")document.documentElement.dataset.theme=themePref;else delete document.documentElement.dataset.theme;let icon=themePref==="dark"?"☾":themePref==="light"?"☀":"◐";ui.theme.textContent=icon;ui.theme.title=`Theme: ${themePref}`;ui.theme.setAttribute("aria-label",`Theme: ${themePref}`);try{localStorage.setItem(THEME_KEY,themePref)}catch{}}
function cycleTheme(){themePref=themePref==="system"?"dark":themePref==="dark"?"light":"system";applyTheme()}
function download(name,content,type){let a=document.createElement("a"),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function undo(){if(!undoStack.length)return;redoStack.push(JSON.stringify(doc));doc=JSON.parse(undoStack.pop());selected=null;render();updateUndo()}function redo(){if(!redoStack.length)return;undoStack.push(JSON.stringify(doc));doc=JSON.parse(redoStack.pop());selected=null;render();updateUndo()}
function loadDemo(d){doc=parseText(d.text);doc.meta={title:d.title,author:d.author,source:d.source,license:d.license,excerpt:!!d.excerpt};undoStack=[];redoStack=[];selected=null;ui.source.value=d.text;showWorkspace();render();ui.demoDialog.close();toast(`${d.author} · ${d.title}`)}
function renderDemos(){let q=ui.demoSearch.value.trim().toLowerCase(),items=DEMOS.filter(d=>`${d.author} ${d.title} ${(d.tags||[]).join(" ")} ${d.license}`.toLowerCase().includes(q));ui.demoList.innerHTML="";ui.demoCount.textContent=`${items.length}/${DEMOS.length}${poemLibraryError?" · fallback":""}`;if(poemLibraryError)ui.demoList.appendChild(el("div","demo-empty","poems.json unavailable here; showing the built-in fallback."));if(!items.length){ui.demoList.appendChild(el("div","demo-empty","No matches."));return}items.forEach(d=>{let row=el("div","demo-row"),main=el("div","demo-main"),title=el("div","demo-title",d.title),meta=el("div","demo-meta");meta.append(el("span","","— "+d.author));(d.tags||[]).slice(0,2).forEach(t=>meta.append(el("span","demo-badge",t)));meta.append(el("span","demo-badge",d.license));main.append(title,meta);let actions=el("div","demo-actions"),load=el("button","demo-load","Load");load.type="button";load.addEventListener("click",()=>loadDemo(d));actions.append(load);if(d.source){let src=document.createElement("a");src.className="demo-source";src.href=d.source;src.target="_blank";src.rel="noopener";src.textContent="source ↗";actions.append(src)}row.append(main,actions);ui.demoList.appendChild(row)})}
function restore(){try{let s=JSON.parse(localStorage.getItem(KEY)||"null");if(!s?.doc?.text)return false;doc=s.doc;Object.assign(settings,s.settings||{});showWorkspace();render();return true}catch{return false}}
ui.demo.addEventListener("click",()=>{ui.demoSearch.value="";renderDemos();ui.demoDialog.showModal();setTimeout(()=>ui.demoSearch.focus(),30)});ui.demoSearch.addEventListener("input",renderDemos);ui.copyMd.addEventListener("click",copyMarkdown);ui.theme.addEventListener("click",cycleTheme);applyTheme();
ui.analyze.addEventListener("click",()=>{let text=ui.source.value.trimEnd();if(!text.trim()){toast("Add some text first.");return}doc=parseText(text);doc.meta=null;undoStack=[];redoStack=[];selected=null;showWorkspace();render()});
$("#viewStrip").addEventListener("click",e=>{let b=e.target.closest("button");if(!b)return;if(b.dataset.toggle)settings[b.dataset.toggle]=!settings[b.dataset.toggle];render()});
ui.context.addEventListener("click",e=>{let b=e.target.closest("button");if(!b)return;if(Object.hasOwn(b.dataset,"stress"))setStress(b.dataset.stress);else if(b.dataset.boundary)setBoundary(b.dataset.boundary)});
ui.syllablesBtn.addEventListener("click",()=>openWord());ui.applyWord.addEventListener("click",applyWord);ui.stats.addEventListener("click",openStats);ui.help.addEventListener("click",()=>$("#helpDialog").showModal());ui.edit.addEventListener("click",()=>{ui.editText.value=doc.text;ui.editDialog.showModal()});ui.applyEdit.addEventListener("click",()=>{let text=ui.editText.value.trimEnd();if(!text.trim()){toast("The poem cannot be empty.");return}pushUndo();doc=reconcile(text);selected=null;ui.editDialog.close();render()});ui.exp.addEventListener("click",()=>ui.exportDialog.showModal());ui.undo.addEventListener("click",undo);ui.redo.addEventListener("click",redo);
$("#copyAnnotatedBtn").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(annotatedText());toast("Copied.")}catch{toast("Clipboard unavailable.")}});$("#downloadTxtBtn").addEventListener("click",()=>download("prosody.txt",annotatedText(),"text/plain;charset=utf-8"));$("#downloadJsonBtn").addEventListener("click",()=>download("prosody.json",JSON.stringify({doc,settings},null,2),"application/json"));$("#newPoemBtn").addEventListener("click",()=>{if(!confirm("Start a new poem? Your current work will be cleared."))return;localStorage.removeItem(KEY);location.reload()});$$('[data-close]').forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.close).close()));
document.addEventListener("keydown",e=>{if(!doc||document.querySelector("dialog[open]"))return;let mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();redo();return}if(!selected)return;if(e.key==="1"){e.preventDefault();setStress("weak")}if(e.key==="2"){e.preventDefault();setStress("medium")}if(e.key==="3"){e.preventDefault();setStress("strong")}if(e.key==="0"||e.key==="Backspace"){e.preventDefault();setStress(null)}if(e.key==="|"){e.preventDefault();setBoundary(e.shiftKey?"caesura":"foot")}});
async function init(){
  await loadPoemLibrary();
  if(!restore()){
    let full=DEMOS.filter(d=>!d.excerpt&&(/public domain/i.test(d.license)||d.author==="Dev"));
    if(!full.length)full=DEMOS;
    loadDemo(full[Math.floor(Math.random()*full.length)]);
  }
}
init();
