import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
function appContext(){const noop=()=>{};const node=()=>({classList:{add:noop,remove:noop,toggle:noop},addEventListener:noop,querySelectorAll:()=>[],setAttribute:noop,append:noop,appendChild:noop,style:{setProperty:noop}});const context=vm.createContext({console,setTimeout,clearTimeout,Uint16Array,document:{querySelector:node,querySelectorAll:()=>[],createElement:node}});for(const f of ["js/prosody.js","js/notation.js","js/render.js"])vm.runInContext(fs.readFileSync(f,"utf8"),context,{filename:f});return context}
function run(ctx,expression){return vm.runInContext(expression,ctx)}
test("ordinary 5-7-5 regression",()=>{const c=appContext();const counts=run(c,`parseText("Maybe it will rain\\nSpiders crawling on my skin\\nCoffee tastes like dirt.").stanzas[0].lines.map(lineStats).map(x=>x.syllables)`);assert.deepEqual([...counts],[5,7,5])});
test("Autumn Referendum remains 5-7-5",()=>{const c=appContext();const counts=run(c,`parseText("Each leaf casts its vote.\\nThe Autumn Referendum\\nThe republic stands.").stanzas[0].lines.map(lineStats).map(x=>x.syllables)`);assert.deepEqual([...counts],[5,7,5])});
test("Jabberwocky opening survives nonce words",()=>{const c=appContext();const counts=run(c,`parseText("'Twas brillig, and the slithy toves\\nDid gyre and gimble in the wabe:\\nAll mimsy were the borogoves,\\nAnd the mome raths outgrabe.").stanzas[0].lines.map(lineStats).map(x=>x.syllables)`);assert.deepEqual([...counts],[8,8,8,6])});
test("Jabberwocky nonce words split plausibly and round-trip",()=>{const c=appContext();const expected={brillig:2,slithy:2,toves:1,gyre:1,gimble:2,borogoves:3,mimsy:2,frumious:3,manxome:2,uffish:2,tulgey:2,frabjous:2,chortled:2,galumphing:3};for(const [word,count] of Object.entries(expected)){assert.equal(run(c,`syllabify(${JSON.stringify(word)}).length`),count,word);assert.equal(run(c,`syllabify(${JSON.stringify(word)}).join("")`),word,word+" round-trip")}});
test("parser preserves stanza and line structure",()=>{const c=appContext();const shape=run(c,`(()=>{let d=parseText("one\\ntwo\\n\\nthree");return [d.stanzas.length,d.stanzas[0].lines.length,d.stanzas[1].lines.length]})()`);assert.deepEqual([...shape],[2,2,1])});
test("manual notation preserves case and encodes stress independently",()=>{const c=appContext();const got=run(c,`(()=>{let d=parseText("[I] <am> [Ve]<ry> <tall>");let s=allSyllables(d);return [d.text,s.map(x=>x.sy.text).join("|"),s.map(x=>x.sy.stress).join("|")]})()`);assert.deepEqual([...got],["I am Very tall","I|am|Ve|ry|tall","strong|weak|strong|weak|weak"])});
test("manual syntax can force four syllables without changing capitalization",()=>{const c=appContext();const got=run(c,`(()=>{let d=parseText("[Sa]<li><enc><cy>");let w=d.stanzas[0].lines[0].segments[0];return [w.raw,w.syllables.length,w.syllables.map(x=>x.stress).join("|")]})()`);assert.deepEqual([...got],["Salienccy",4,"strong|weak|weak|weak"])});
test("escaped delimiters remain literal text",()=>{const c=appContext();const got=run(c,String.raw`parseText("Use \\[this\\] and \\<that\\> literally").text`);assert.equal(got,"Use [this] and <that> literally")});
test("source and ordinary capitalization are preserved",()=>{const c=appContext();const got=run(c,`(()=>{let d=parseText("McDONALD iPhone\\n[Odd]<Case>");return [d.source,d.text]})()`);assert.deepEqual([...got],["McDONALD iPhone\n[Odd]<Case>","McDONALD iPhone\nOddCase"])});
test("render pieces preserve ordinary Getting exactly",()=>{const c=appContext();const got=run(c,`(()=>{const seg=parseText("Getting").stanzas[0].lines[0].segments[0];return [seg.raw,sourcePieces(seg).join("")]})()`);assert.deepEqual([...got],["Getting","Getting"])});
test("render pieces preserve manual [Gett]<ing> exactly",()=>{const c=appContext();const got=run(c,`(()=>{const seg=parseText("[Gett]<ing>").stanzas[0].lines[0].segments[0];return [seg.raw,sourcePieces(seg).join(""),seg.syllables.map(x=>x.stress).join("|")]})()`);assert.deepEqual([...got],["Getting","Getting","strong|weak"])});
test("render pieces recover exact source spelling from bad syllable lengths",()=>{const c=appContext();const got=run(c,`sourcePieces({raw:"Getting",syllables:[{text:"Get"},{text:"thing"}]}).join("")`);assert.equal(got,"Getting")});
test("annotated plaintext round-trips case with bracket semantics",()=>{const c=appContext();const got=run(c,`annotatedText(parseText("[Ve]<ry> nice"))`);assert.equal(got,"[Ve]<ry> nice\n\n— Anonymous")});
test("canonical syllable separator is U+00B7 middle dot",()=>{const c=appContext();assert.equal(run(c,"SYLLABLE_DOT"),"·");const got=run(c,`(()=>{const seg=parseText("[Ve]<ry>").stanzas[0].lines[0].segments[0];return [seg.syllables.length,sourcePieces(seg).join(SYLLABLE_DOT)]})()`);assert.deepEqual([...got],[2,"Ve·ry"])});
test("expanded formatting settings clamp and recover invalid saved values",()=>{const c=appContext();const hi=run(c,`migrateSettings({fontSize:99,lineHeight:9,symbolScale:9,syllableGap:9,typeStrength:9})`),lo=run(c,`migrateSettings({fontSize:1,lineHeight:.1,symbolScale:.1,syllableGap:-1,typeStrength:-1})`),bad=run(c,`migrateSettings({fontSize:undefined,lineHeight:"x",symbolScale:null,syllableGap:undefined,typeStrength:"nope"})`);assert.deepEqual([hi.fontSize,hi.lineHeight,hi.symbolScale,hi.syllableGap,hi.typeStrength],[42,2,2.2,.32,1.4]);assert.deepEqual([lo.fontSize,lo.lineHeight,lo.symbolScale,lo.syllableGap,lo.typeStrength],[12,.9,.4,0,0]);assert.deepEqual([bad.fontSize,bad.lineHeight,bad.symbolScale,bad.syllableGap,bad.typeStrength],[22,1.29,1,.04,.75])});
test("legacy structure toggles do not override the current Summary setting",()=>{const c=appContext();assert.equal(run(c,`migrateSettings({stanzas:true,boundaries:true}).structure`),false);assert.equal(run(c,`migrateSettings({structure:true,stanzas:false,boundaries:false}).structure`),true)});
test("reconcile reparses notation and strips demo metadata",()=>{const c=appContext();const got=run(c,`(()=>{doc=parseText("old");doc.meta={title:"T",author:"A",source:"U"};let n=reconcile("[New]");return [n.source,n.text,n.stanzas[0].lines[0].segments[0].syllables[0].stress,n.meta.title,n.meta.author,n.meta.source,n.meta.edited]})()`);assert.deepEqual([...got],["[New]","New","strong",undefined,"Anonymous","",true])});
